export const SET_DID_ITEMS = 'SET_DID_ITEMS';
export const SET_EDIT_DID_ITEM_ID = 'SET_EDIT_DID_ITEM_ID';
export const SET_WAS_DID_ITEM_ADDED = 'SET_WAS_DID_ITEM_ADDED';
export const SET_BLOCK_CRITICAL_LAYOUT_PARTS =
  'SET_BLOCK_CRITICAL_LAYOUT_PARTS';
